### ISSUE TITLE
Add maxSize option to ArrayCache

### ISSUE THREAD

**Issue by kelunik** [amphp/cache#4]
We should add `$maxSize` to `ArrayCache` or provide a second implementation of `ArrayCache` that allows for such an option to limit the size of the cache. `amphp/dns` is one component that potentially benefits from such an option to limit the cache size, otherwise the cache might grow indefinitely if a client always requests new hostnames and they have a high TTL.

**Comment by duckoder** [comment]
@kelunik hi, I can help you with this. Can you just describe how you see it ?

**Comment by kelunik** [comment]
@zhikiri Awesome! For limiting the number of items in the cache (not its exact size), it just needs a few small changes:

https://github.com/amphp/cache/blob/d6ab81ce35019b0fd84ca6d665fd4817bfd11701/lib/ArrayCache.php#L89

Here it needs to `unset()` the key before setting it, to make sure it's at the end of the array. If there's a `$maxSize` and the size of the array is larger than `$maxSize`, it needs to shift the first item in the array. That'll give us a LRU implementation.

**Comment by duckoder** [comment]
@kelunik Got it.

**Comment by duckoder** [comment]
@kelunik here is the PR for this https://github.com/amphp/cache/pull/5

**Comment by kelunik** [comment]
Resolved via #5.
